# A new Azure Devops project will be created with the following configuration values.
# You can, but don't have to edit these
ado_project_name: "MigrateFromADO2"
ado_repository_name: "MigrateFromADORepo2"

# Update these values before running the bootstrap script

ado_url: "https://dev.azure.com/yuriromao"  # e.g "https://dev.azure.com/your-org"

github_org: "Projeto-Testee"
target_github_repo_name: "migrated-repo"